In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/AI Training/Datasets/Copy of healthcare-dataset-stroke-data.csv')

In [ ]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [ ]:
x=df.iloc[:,1:-1]
y=df.iloc[:,-1]

In [ ]:
x.head()

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked
1,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked
2,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked
3,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes
4,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked

In [ ]:
x.shape

(5110, 10)

In [ ]:
y.shape

(5110,)

In [ ]:
from sklearn.model_selection import train_test_split


x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=42)
cols=x_train.columns.to_list()

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
df.select_dtypes(include='object').columns.to_list()

['gender', 'ever_married', 'work_type', 'Residence_type', 'smoking_status']

In [ ]:
y_test.value_counts()

stroke
0    960
1     62
Name: count, dtype: int64

In [ ]:
x_train.select_dtypes(include='object').columns.to_list()

['gender', 'ever_married', 'work_type', 'Residence_type', 'smoking_status']

In [ ]:
x_test.select_dtypes(include='object').columns.to_list()

['gender', 'ever_married', 'work_type', 'Residence_type', 'smoking_status']

In [ ]:
x_test=x_test[x_test['gender']!='Other']

In [ ]:
le=LabelEncoder()

object_cols = x_train.select_dtypes(include='object').columns.to_list()

for i in object_cols:

  x_train[i]=le.fit_transform(x_train[i])
  x_test[i]=le.transform(x_test[i])

  # print(x_train[i].value_counts())
  # print("_____________________-------_____-------____------")
  # print(x_test[i].value_counts())
  # print()
  # print()

In [ ]:
x_test.head()

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status
4688,1,31.0,0,0,0,3,0,64.85,23.0,0
4478,1,40.0,0,0,1,3,0,65.29,28.3,2
3849,0,8.0,0,0,0,4,1,74.42,22.5,0
4355,0,79.0,1,0,1,3,0,76.64,19.5,2
3826,0,75.0,0,0,1,0,0,94.77,27.2,2

In [ ]:
cols

['gender',
 'age',
 'hypertension',
 'heart_disease',
 'ever_married',
 'work_type',
 'Residence_type',
 'avg_glucose_level',
 'bmi',
 'smoking_status']

In [ ]:
sc=StandardScaler()
for i in cols:
  x_train[i]=sc.fit_transform(x_train[[i]])
  x_test[i]=sc.transform(x_test[[i]])

In [ ]:
y_test.value_counts()

stroke
0    960
1     62
Name: count, dtype: int64

In [ ]:
x_test.shape

(1021, 10)

In [ ]:
y_test=y_test.iloc[:-1]

In [ ]:
from imblearn.over_sampling import RandomOverSampler

In [ ]:
os=RandomOverSampler()
x_test_sampled, y_test_sampled=os.fit_resample(x_test, y_test)

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [ ]:
model=keras.Sequential([
    layers.Flatten(input_shape=(10,)),
    layers.Dense(20, activation='relu'),
    layers.Dense(2, activation='softmax')]
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [ ]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
# sparse_categorical_crossentropy

In [ ]:
model.fit(x_train, y_train, validation_split=0.1, epochs=10)

Epoch 1/10
115/115 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9361 - loss: nan - val_accuracy: 0.9487 - val_loss: nan
Epoch 2/10
115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9549 - loss: nan - val_accuracy: 0.9487 - val_loss: nan
Epoch 3/10
115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9549 - loss: nan - val_accuracy: 0.9487 - val_loss: nan
Epoch 4/10
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9549 - loss: nan - val_accuracy: 0.9487 - val_loss: nan
Epoch 5/10
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9549 - loss: nan - val_accuracy: 0.9487 - val_loss: nan
Epoch 6/10
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9549 - loss: nan - val_accuracy: 0.9487 - val_loss: nan
Epoch 7/10
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9549 - loss: nan - val_accuracy: 0.9487 - val_loss: nan
Epoch 8/10
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9549 - loss: nan - val_accuracy: 0.9487 - val_loss: nan
Epoch 9/10
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9549 - loss: nan - val_accuracy: 0.9487 - val_loss: nan
Epoch 10/10
115/115 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9549 - loss: nan - val_accuracy: 0.9487 - val_loss: nan

In [ ]:
loss, accuracy=model.evaluate(x_test, y_test)

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9393 - loss: nan

In [ ]:
print(accuracy)

0.9392752051353455