In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('/content/drive/MyDrive/AI Training/Datasets/Copy of Market_Basket_Optimisation.csv', header=None)

In [4]:
df.shape

(7501, 20)

In [5]:
df.isnull().sum()

0        0
1     1754
2     3112
3     4156
4     4972
5     5637
6     6132
7     6520
8     6847
9     7106
10    7245
11    7347
12    7414
13    7454
14    7476
15    7493
16    7497
17    7497
18    7498
19    7500
dtype: int64

In [6]:
df.shape

(7501, 20)

In [7]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.iloc[1]

0       burgers
1     meatballs
2          eggs
3           NaN
4           NaN
5           NaN
6           NaN
7           NaN
8           NaN
9           NaN
10          NaN
11          NaN
12          NaN
13          NaN
14          NaN
15          NaN
16          NaN
17          NaN
18          NaN
19          NaN
Name: 1, dtype: object

In [9]:
df.iloc[2].isnull().sum()

np.int64(19)

In [10]:
transaction=[]

for i in range(len(df)):
  transaction.append([i for i in df.iloc[i] if not pd.isna(i)])

In [11]:
print(transaction[1])

['burgers', 'meatballs', 'eggs']

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7501 entries, 0 to 7500
Data columns (total 20 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       7501 non-null   object
 1   1       5747 non-null   object
 2   2       4389 non-null   object
 3   3       3345 non-null   object
 4   4       2529 non-null   object
 5   5       1864 non-null   object
 6   6       1369 non-null   object
 7   7       981 non-null    object
 8   8       654 non-null    object
 9   9       395 non-null    object
 10  10      256 non-null    object
 11  11      154 non-null    object
 12  12      87 non-null     object
 13  13      47 non-null     object
 14  14      25 non-null     object
 15  15      8 non-null      object
 16  16      4 non-null      object
 17  17      4 non-null      object
 18  18      3 non-null      object
 19  19      1 non-null      object
dtypes: object(20)
memory usage: 1.1+ MB

In [13]:
print(type(transaction[2][0]))

<class 'str'>

In [14]:
!pip install apyori

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5954 sha256=3eac5db06a8917639ddaaf06a1c354236d8ae0370fbf6b5dc61e2be2a7616ccc
  Stored in directory: /root/.cache/pip/wheels/7f/49/e3/42c73b19a264de37129fadaa0c52f26cf50e87de08fb9804af
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [15]:
len(transaction)

7501

In [16]:
from apyori import apriori

In [17]:
rules=apriori(transactions=transaction, min_support=0.001, min_confidence=0.1, min_lift=2, min_length=2, max_length=2)
results=list(rules)

In [18]:
len(results)

285

In [19]:
rules

In [20]:
# print(results[0])
for i in results[0]:
  print(i)

frozenset({'burgers', 'almonds'})
0.005199306759098787
[OrderedStatistic(items_base=frozenset({'almonds'}), items_add=frozenset({'burgers'}), confidence=0.25490196078431376, lift=2.923577382023146)]

In [21]:
li=((list(results[0])))

In [22]:
for i in range(len((list(results[0])))):
  print(li[i])

frozenset({'burgers', 'almonds'})
0.005199306759098787
[OrderedStatistic(items_base=frozenset({'almonds'}), items_add=frozenset({'burgers'}), confidence=0.25490196078431376, lift=2.923577382023146)]

In [23]:
li2=((list(results[1])))

In [24]:
print(list(results[1]))

[frozenset({'frozen smoothie', 'almonds'}), 0.0027996267164378083, [OrderedStatistic(items_base=frozenset({'almonds'}), items_add=frozenset({'frozen smoothie'}), confidence=0.13725490196078433, lift=2.1674716202270385)]]

In [25]:
for i in range(len((list(results[1])[2]))):
  print(li2[2][i])

OrderedStatistic(items_base=frozenset({'almonds'}), items_add=frozenset({'frozen smoothie'}), confidence=0.13725490196078433, lift=2.1674716202270385)

In [26]:
li=[]
for i in results:
  # for j in range(len(list(i))):
    df={}
    df['lhs']=list(i[2][0][0])[0]
    df['rhs']=list(i[2][0][1])[0]
    df['support']=i[1]
    df['confidence']=i[2][0][2]
    df['lift']=i[2][0][3]
    # print(i[j])

In [27]:
print(len(results))

285

In [28]:
li=[]
for i in results:
  # for j in range(len(list(i))):
    xdf={}
    xdf['lhs']=list(i[2][0][0])[0]
    xdf['rhs']=list(i[2][0][1])[0]
    xdf['support']=i[1]
    xdf['confidence']=i[2][0][2]
    xdf['lift']=i[2][0][3]
    li.append(xdf)
    # print(i[j])

In [29]:
pd.DataFrame(li)

                   lhs                rhs   support  confidence      lift
0              almonds            burgers  0.005199    0.254902  2.923577
1              almonds    frozen smoothie  0.002800    0.137255  2.167472
2              almonds          olive oil  0.002933    0.143791  2.183351
3              almonds               soup  0.002266    0.111111  2.199062
4    antioxydant juice            cereals  0.001466    0.164179  6.380868
..                 ...                ...       ...         ...       ...
280      strong cheese          spaghetti  0.003733    0.482759  2.772720
281                tea          spaghetti  0.001466    0.379310  2.178566
282       tomato sauce          spaghetti  0.006266    0.443396  2.546642
283   whole weat flour           tomatoes  0.001333    0.142857  2.088833
284               yams  whole wheat pasta  0.001200    0.104651  3.551984

[285 rows x 5 columns]

In [30]:
for i in (results[0]):
  print(i)

frozenset({'burgers', 'almonds'})
0.005199306759098787
[OrderedStatistic(items_base=frozenset({'almonds'}), items_add=frozenset({'burgers'}), confidence=0.25490196078431376, lift=2.923577382023146)]

In [31]:
for i in results:
  print(list(i[2][0][0])[0])
  print(list(i[2][0][1])[0])
  print(i[1])
  print(i[2][0][2])
  print(i[2][0][3])

almonds
burgers
0.005199306759098787
0.25490196078431376
2.923577382023146
almonds
frozen smoothie
0.0027996267164378083
0.13725490196078433
2.1674716202270385
almonds
olive oil
0.0029329422743634183
0.14379084967320263
2.1833505331957346
almonds
soup
0.0022663644847353685
0.1111111111111111
2.1990618586924655
antioxydant juice
cereals
0.0014664711371817091
0.16417910447761194
6.38086768231382
antioxydant juice
frozen smoothie
0.0011998400213304892
0.1343283582089552
2.121256873527101
asparagus
milk
0.0013331555792560992
0.2857142857142857
2.2048794826572604
avocado
frozen smoothie
0.005065991201173177
0.152
2.4003200000000002
melons
avocado
0.0013331555792560992
0.11111111111111112
3.3337777777777777
avocado
soup
0.004399413411545127
0.132
2.6124854881266493
toothpaste
avocado
0.0010665244634048793
0.13114754098360656
3.9349508196721312
yams
avocado
0.0011998400213304892
0.10465116279069768
3.139953488372093
babies food
chocolate
0.0017331022530329288
0.3823529411764706
2.3336284880103384
bacon
barbecue sauce
0.0011998400213304892
0.13846153846153847
12.822222222222223
bacon
burgers
0.001999733368884149
0.2307692307692308
2.6467889908256885
bacon
chicken
0.0011998400213304892
0.13846153846153847
2.3080000000000003
bacon
cooking oil
0.001599786695107319
0.18461538461538463
3.6156657963446475
bacon
ground beef
0.0021330489268097585
0.24615384615384614
2.5052917232021708
bacon
herb & pepper
0.0010665244634048793
0.12307692307692307
2.488409703504043
bacon
olive oil
0.0011998400213304892
0.13846153846153847
2.102429149797571
bacon
pancakes
0.0021330489268097585
0.24615384615384614
2.589621318373071
bacon
red wine
0.0010665244634048793
0.12307692307692307
4.375355450236967
bacon
spaghetti
0.003199573390214638
0.36923076923076925
2.1206738131699847
bacon
turkey
0.0011998400213304892
0.13846153846153847
2.214498933901919
bacon
whole wheat rice
0.0013331555792560992
0.15384615384615385
2.62870159453303
barbecue sauce
burgers
0.001999733368884149
0.1851851851851852
2.1239664741193796
barbecue sauce
butter
0.0011998400213304892
0.1111111111111111
3.687807276302851
barbecue sauce
cooking oil
0.0011998400213304892
0.1111111111111111
2.1760951552074266
barbecue sauce
ground beef
0.0021330489268097585
0.19753086419753085
2.0104192840511246
barbecue sauce
soup
0.0013331555792560992
0.12345679012345678
2.4434020652138506
barbecue sauce
turkey
0.0025329956005865884
0.2345679012345679
3.751585985416831
black tea
chicken
0.0017331022530329288
0.12149532710280372
2.025192107995846
black tea
herb & pepper
0.001999733368884149
0.14018691588785048
2.834345164622012
black tea
milk
0.004266097853619517
0.29906542056074764
2.3079112341833006
black tea
turkey
0.001999733368884149
0.14018691588785048
2.242093936193532
blueberries
chicken
0.0011998400213304892
0.13043478260869565
2.1742028985507247
blueberries
cooking oil
0.0011998400213304892
0.13043478260869565
2.5545464865478484
blueberries
escalope
0.0017331022530329288
0.18840579710144928
2.3751796370722205
blueberries
grated cheese
0.0014664711371817091
0.15942028985507248
3.0427775933915995
blueberries
ground beef
0.0023996800426609784
0.2608695652173913
2.6550645979588223
blueberries
light cream
0.0010665244634048793
0.11594202898550723
7.433172302737519
blueberries
olive oil
0.0014664711371817091
0.15942028985507248
2.420671243325706
blueberries
soup
0.0013331555792560992
0.14492753623188406
2.8683415548162596
blueberries
spaghetti
0.0034662045060658577
0.37681159420289856
2.164214217546663
body spray
french fries
0.004266097853619517
0.37209302325581395
2.17712150346479
body spray
soup
0.0018664178109585388
0.16279069767441862
3.221881327851752
brownies
cottage cheese
0.0034662045060658577
0.10276679841897232
3.225329518580382
bug spray
chicken
0.001599786695107319
0.18461538461538463
3.0773333333333337
bug spray
ground beef
0.0018664178109585388
0.2153846153846154
2.1921302578019
bug spray
olive oil
0.0014664711371817091
0.16923076923076924
2.5696356275303645
bug spray
shrimp
0.0013331555792560992
0.15384615384615385
2.1529850746268657
burger sauce
chicken
0.001599786695107319
0.2727272727272727
4.546060606060606
burger sauce
frozen smoothie
0.0010665244634048793
0.1818181818181818
2.8711961722488035
burger sauce
ground beef
0.0014664711371817091
0.25
2.544436906377205
burger sauce
shrimp
0.0010665244634048793
0.1818181818181818
2.5444369063772045
burger sauce
spaghetti
0.0023996800426609784
0.40909090909090906
2.3496101907281077
cider
burgers
0.0021330489268097585
0.20253164556962025
2.3229202957457513
corn
burgers
0.0011998400213304892
0.25
2.867354740061162
french wine
burgers
0.0041327822956939075
0.1834319526627219
2.103857915784521
ham
burgers
0.005599253432875617
0.21105527638190955
2.420681388594348
butter
chicken
0.004266097853619517
0.1415929203539823
2.360196656833825
fresh tuna
cake
0.0037328356219170776
0.16766467065868262
2.0685077213993064
fromage blanc
cake
0.0023996800426609784
0.1764705882352941
2.1771478328173375
pet food
cake
0.0010665244634048793
0.16326530612244897
2.0142320085929106
toothpaste
cake
0.0017331022530329288
0.21311475409836064
2.629233175150992
carrots
ham
0.001599786695107319
0.10434782608695653
3.9332313742626175
carrots
herb & pepper
0.0017331022530329288
0.11304347826086956
2.2855502168053436
carrots
oil
0.001599786695107319
0.10434782608695653
4.524352852475497
carrots
salmon
0.001999733368884149
0.13043478260869568
3.0670573804007093
carrots
shrimp
0.0023996800426609784
0.1565217391304348
2.1904282933160286
carrots
turkey
0.0025329956005865884
0.16521739130434784
2.6424214332066382
carrots
whole wheat rice
0.001999733368884149
0.13043478260869568
2.2286817866693083
cauliflower
ground beef
0.0011998400213304892
0.25
2.544436906377205
cereals
cooking oil
0.0029329422743634183
0.1139896373056995
2.2324706773630596
cereals
fresh bread
0.0027996267164378083
0.10880829015544043
2.526845153114423
cereals
herb & pepper
0.003199573390214638
0.12435233160621763
2.5141963325558985
cereals
milk
0.007065724570057326
0.2746113989637306
2.119197637476279
chili
chicken
0.0011998400213304892
0.19565217391304346
3.2613043478260866
cider
chicken
0.0013331555792560992
0.12658227848101267
2.109985935302391
chicken
cooking oil
0.006799093454206106
0.11333333333333334
2.2196170583115755
eggplant
chicken
0.0021330489268097585
0.1616161616161616
2.693961840628507
extra dark chocolate
chicken
0.0027996267164378083
0.23333333333333334
3.8894074074074076
fresh bread
chicken
0.005199306759098787
0.12074303405572756
2.0126522187822498
fromage blanc
chicken
0.0018664178109585388
0.1372549019607843
2.2878867102396514
light cream
chicken
0.004532728969470737
0.29059829059829057
4.84395061728395
magazines
chicken
0.001999733368884149
0.1829268292682927
3.0491869918699193
meatballs
chicken
0.003199573390214638
0.15286624203821658
2.548110403397028
nonfat milk
chicken
0.0013331555792560992
0.1282051282051282
2.137037037037037
rice
chicken
0.0025329956005865884
0.1347517730496454
2.2461623325453113
toothpaste
chicken
0.0010665244634048793
0.13114754098360656
2.1860837887067395
white wine
chicken
0.0021330489268097585
0.12903225806451613
2.1508243727598564
whole weat flour
chicken
0.0017331022530329288
0.1857142857142857
3.0956507936507935
chili
ground beef
0.0013331555792560992
0.21739130434782608
2.212553831632352
chili
pancakes
0.0011998400213304892
0.19565217391304346
2.0583267272394656
chili
shrimp
0.0011998400213304892
0.19565217391304346
2.738035366645035
chili
spaghetti
0.0023996800426609784
0.3913043478260869
2.2474532259138424
chili
tomatoes
0.0010665244634048793
0.17391304347826084
2.5429273667259933
tomato sauce
chocolate
0.005065991201173177
0.3584905660377358
2.1879883936932925
chocolate bread
red wine
0.0010665244634048793
0.25
8.887440758293838
chutney
spaghetti
0.0014664711371817091
0.3548387096774194
2.0380131403448107
cider
eggs
0.004266097853619517
0.4050632911392405
2.2539909101153137
cider
herb & pepper
0.0010665244634048793
0.10126582278481013
2.0474257054147187
cider
milk
0.003332888948140248
0.31645569620253167
2.4421133510444344
cider
whole wheat rice
0.0014664711371817091
0.13924050632911394
2.3791413165710336
clothes accessories
fresh bread
0.0010665244634048793
0.12698412698412698
2.948940979900732
clothes accessories
frozen smoothie
0.0011998400213304892
0.14285714285714285
2.25593984962406
clothes accessories
green tea
0.0023996800426609784
0.2857142857142857
2.1626063139685745
clothes accessories
herb & pepper
0.0013331555792560992
0.15873015873015872
3.2092585461857697
clothes accessories
shrimp
0.001599786695107319
0.19047619047619047
2.665600568585643
clothes accessories
whole wheat rice
0.0010665244634048793
0.12698412698412698
2.1697219510431354
shallot
cookies
0.001999733368884149
0.25862068965517243
3.2171041344999143
extra dark chocolate
cooking oil
0.001599786695107319
0.13333333333333336
2.6113141862489124
fromage blanc
cooking oil
0.0014664711371817091
0.10784313725490197
2.1120923565248555
cooking oil
grated cheese
0.005732568990801226
0.11227154046997388
2.1428723284103666
cooking oil
herb & pepper
0.005332622317024397
0.10443864229765012
2.111574813678365
light cream
cooking oil
0.0027996267164378083
0.1794871794871795
3.5152306353350737
magazines
cooking oil
0.0013331555792560992
0.12195121951219513
2.388397121569127
nonfat milk
cooking oil
0.0013331555792560992
0.1282051282051282
2.5108790252393383
oil
cooking oil
0.0026663111585121984
0.11560693641618497
2.264145248192698
protein bar
cooking oil
0.0021330489268097585
0.11510791366906474
2.2543719593515785
rice
cooking oil
0.0021330489268097585
0.11347517730496452
2.2223950521267333
cooking oil
soup
0.005332622317024397
0.10443864229765012
2.067003313653492
tomato sauce
cooking oil
0.0014664711371817091
0.10377358490566038
2.032390758165427
toothpaste
cooking oil
0.0018664178109585388
0.22950819672131148
4.4948850746907505
zucchini
cooking oil
0.0014664711371817091
0.15492957746478872
3.034273526275144
corn
tomatoes
0.0010665244634048793
0.2222222222222222
3.249296079705436
cottage cheese
frozen smoothie
0.004932675643247567
0.15481171548117154
2.4447214269984583
dessert wine
salmon
0.0010665244634048793
0.2424242424242424
5.700389474684145
eggplant
whole wheat rice
0.0021330489268097585
0.1616161616161616
2.761464301327627
mushroom cream sauce
escalope
0.005732568990801226
0.3006993006993007
3.790832696715049
pasta
escalope
0.005865884548726837
0.3728813559322034
4.700811850163794
shallot
escalope
0.0018664178109585388
0.2413793103448276
3.043002028397566
extra dark chocolate
herb & pepper
0.0011998400213304892
0.1
2.021832884097035
extra dark chocolate
honey
0.0014664711371817091
0.12222222222222223
2.575249687890137
extra dark chocolate
light cream
0.001599786695107319
0.13333333333333336
8.54814814814815
extra dark chocolate
mineral water
0.005732568990801226
0.47777777777777775
2.0043686303753416
extra dark chocolate
olive oil
0.0026663111585121984
0.22222222222222224
3.3742690058479536
extra dark chocolate
pancakes
0.0023996800426609784
0.2
2.1040673211781207
extra dark chocolate
salmon
0.0013331555792560992
0.11111111111111112
2.6126785092302334
extra dark chocolate
shrimp
0.0018664178109585388
0.15555555555555556
2.1769071310116086
flax seed
green tea
0.0030662578322890282
0.3382352941176471
2.560144239330445
shallot
french fries
0.0026663111585121984
0.3448275862068966
2.017591048469525
french wine
fresh bread
0.0027996267164378083
0.1242603550295858
2.8856870683496068
french wine
fresh tuna
0.0025329956005865884
0.11242603550295857
5.049746660525103
green beans
french wine
0.0010665244634048793
0.12307692307692307
5.462721893491124
french wine
honey
0.0022663644847353685
0.10059171597633135
2.119490060501296
french wine
olive oil
0.0034662045060658577
0.15384615384615383
2.336032388663967
magazines
fresh bread
0.0011998400213304892
0.10975609756097561
2.548855999395907
salt
fresh bread
0.0010665244634048793
0.11594202898550723
2.692511329474581
tomato juice
fresh bread
0.004266097853619517
0.14035087719298245
3.2593558198902826
white wine
fresh bread
0.0021330489268097585
0.12903225806451613
2.996504544092679
fresh tuna
fromage blanc
0.0023996800426609784
0.10778443113772455
7.926382529059528
fresh tuna
frozen smoothie
0.0029329422743634183
0.1317365269461078
2.080327765521589
fresh tuna
honey
0.003999466737768298
0.17964071856287428
3.7850703088205613
fresh tuna
olive oil
0.0037328356219170776
0.16766467065868262
2.5458556571068387
fresh tuna
pancakes
0.005065991201173177
0.2275449101796407
2.3938490480469636
fromage blanc
frozen smoothie
0.001999733368884149
0.14705882352941177
2.322291021671827
fromage blanc
frozen vegetables
0.0026663111585121984
0.19607843137254902
2.057040998217469
fromage blanc
honey
0.003332888948140248
0.2450980392156863
5.164270764485569
green beans
frozen smoothie
0.0013331555792560992
0.15384615384615385
2.4294736842105267
gums
frozen smoothie
0.0025329956005865884
0.18811881188118812
2.9706930693069307
hot dogs
frozen smoothie
0.004799360085321957
0.14814814814814814
2.339493177387914
mint
frozen smoothie
0.0022663644847353685
0.1297709923664122
2.049288871032543
rice
frozen smoothie
0.0025329956005865884
0.1347517730496454
2.1279432624113475
sparkling water
frozen smoothie
0.0014664711371817091
0.23404255319148937
3.6959014557670775
spinach
frozen smoothie
0.0011998400213304892
0.16981132075471697
2.681588877855015
vegetables mix
frozen smoothie
0.003332888948140248
0.1295336787564767
2.0455413144259618
whole weat flour
frozen smoothie
0.001599786695107319
0.17142857142857143
2.707127819548872
green grapes
frozen vegetables
0.0021330489268097585
0.23529411764705882
2.4684491978609624
nonfat milk
frozen vegetables
0.001999733368884149
0.19230769230769232
2.0174825174825175
parmesan cheese
frozen vegetables
0.005465937874950006
0.27516778523489926
2.886760219646125
frozen vegetables
shrimp
0.01666444474070124
0.17482517482517482
2.4465739484396196
strong cheese
frozen vegetables
0.001599786695107319
0.20689655172413796
2.1705329153605017
tea
frozen vegetables
0.0013331555792560992
0.3448275862068966
3.6175548589341693
frozen vegetables
tomatoes
0.0161311825089988
0.1692307692307692
2.4744639376218323
gluten free bar
grated cheese
0.0010665244634048793
0.15384615384615385
2.9363867684478375
gluten free bar
light mayo
0.0010665244634048793
0.15384615384615385
5.6568627450980395
gluten free bar
pancakes
0.0021330489268097585
0.3076923076923077
3.2370266479663394
grated cheese
ground beef
0.011331822423676844
0.2162849872773537
2.201294015695292
grated cheese
herb & pepper
0.006532462338354886
0.12468193384223919
2.5208603389505018
nonfat milk
grated cheese
0.0018664178109585388
0.17948717948717946
3.425784563189143
rice
grated cheese
0.0025329956005865884
0.1347517730496454
2.57194160215112
salmon
grated cheese
0.005199306759098787
0.12225705329153606
2.333460958625476
tomato sauce
grated cheese
0.001999733368884149
0.14150943396226418
2.700921791732681
green beans
red wine
0.0011998400213304892
0.13846153846153847
4.9222748815165875
green beans
shrimp
0.0013331555792560992
0.15384615384615385
2.1529850746268657
green beans
spaghetti
0.0034662045060658577
0.39999999999999997
2.29739663093415
green grapes
salmon
0.0014664711371817091
0.16176470588235295
3.8037525354969577
green grapes
soup
0.0010665244634048793
0.11764705882352941
2.3284184386155515
green grapes
vegetables mix
0.0014664711371817091
0.16176470588235295
6.287031392868029
magazines
green tea
0.0029329422743634183
0.2682926829268293
2.030740075311954
pickles
green tea
0.0017331022530329288
0.28888888888888886
2.1866352730126697
shallot
green tea
0.0022663644847353685
0.29310344827586204
2.2185357876056924
ground beef
herb & pepper
0.015997866951073192
0.1628222523744912
3.291993841134928
light cream
ground beef
0.003332888948140248
0.2136752136752137
2.174732398612996
oatmeal
ground beef
0.0010665244634048793
0.2424242424242424
2.4673327576991078
ground beef
olive oil
0.014131449140114652
0.14382632293080055
2.183889166607156
pepper
ground beef
0.006532462338354886
0.24623115577889446
2.5060785610549354
pet food
ground beef
0.0013331555792560992
0.20408163265306123
2.0770913521446572
rice
ground beef
0.004399413411545127
0.23404255319148934
2.3820260400127022
salmon
ground beef
0.008932142381015865
0.21003134796238246
2.137646053006555
ground beef
spaghetti
0.03919477403012932
0.3989145183175034
2.291162176033379
tomato sauce
ground beef
0.005332622317024397
0.3773584905660377
3.840659481324083
toothpaste
ground beef
0.0017331022530329288
0.21311475409836064
2.1690281824854862
yams
ground beef
0.0026663111585121984
0.23255813953488375
2.366918052443912
gums
honey
0.0014664711371817091
0.10891089108910891
2.2947769496050725
gums
low fat yogurt
0.0023996800426609784
0.1782178217821782
2.3289405595611825
gums
salmon
0.001599786695107319
0.11881188118811882
2.793755237592725
gums
soup
0.0014664711371817091
0.10891089108910891
2.1555160793124166
ham
olive oil
0.0035995200639914677
0.13567839195979897
2.060169267389579
ham
whole wheat rice
0.004266097853619517
0.1608040201005025
2.7475875962958294
hand protein bar
protein bar
0.0011998400213304892
0.23076923076923075
12.453237410071942
hand protein bar
tomatoes
0.0011998400213304892
0.23076923076923075
3.3742690058479528
light cream
herb & pepper
0.0022663644847353685
0.14529914529914528
2.9377058999700503
protein bar
herb & pepper
0.001999733368884149
0.10791366906474821
2.1818340475867286
rice
herb & pepper
0.0029329422743634183
0.15602836879432624
3.1546328688038843
tomato sauce
herb & pepper
0.0023996800426609784
0.16981132075471697
3.433301123938361
toothpaste
herb & pepper
0.0010665244634048793
0.13114754098360656
2.6515841102911937
whole weat flour
herb & pepper
0.0011998400213304892
0.12857142857142856
2.599499422410473
whole wheat pasta
herb & pepper
0.0037328356219170776
0.12669683257918551
2.5615982241953383
yams
herb & pepper
0.0013331555792560992
0.11627906976744187
2.3509684698802733
protein bar
honey
0.001999733368884149
0.10791366906474821
2.273765257456956
whole weat flour
honey
0.0014664711371817091
0.15714285714285714
3.311035313001605
sparkling water
hot dogs
0.001599786695107319
0.25531914893617025
7.8812713422642515
ketchup
milk
0.0013331555792560992
0.30303030303030304
2.3385085422122462
ketchup
pancakes
0.001599786695107319
0.36363636363636365
3.825576947596583
ketchup
turkey
0.0010665244634048793
0.2424242424242424
3.8772371906700265
light cream
oil
0.0017331022530329288
0.1111111111111111
4.817597944765574
light cream
olive oil
0.003199573390214638
0.20512820512820515
3.1147098515519573
light cream
pancakes
0.0034662045060658577
0.2222222222222222
2.3378525790868006
light cream
shrimp
0.0025329956005865884
0.1623931623931624
2.2725953565505805
light cream
soup
0.0025329956005865884
0.1623931623931624
3.214013485781296
light mayo
pancakes
0.005465937874950006
0.20098039215686272
2.1143813766740918
shallot
low fat yogurt
0.0017331022530329288
0.22413793103448276
2.929021987264208
whole weat flour
low fat yogurt
0.0014664711371817091
0.15714285714285714
2.0535340965654556
magazines
salmon
0.0013331555792560992
0.12195121951219513
2.8675739735453782
mashed potato
spaghetti
0.0014664711371817091
0.3548387096774194
2.0380131403448107
mayonnaise
mineral water
0.0029329422743634183
0.4782608695652174
2.0063952922867427
mayonnaise
pancakes
0.0011998400213304892
0.19565217391304346
2.0583267272394656
meatballs
milk
0.005465937874950006
0.2611464968152866
2.0152879347854578
meatballs
tomatoes
0.0038661511798426876
0.18471337579617836
2.700848015296557
meatballs
turkey
0.0026663111585121984
0.12738853503184713
2.0374017084731033
mint green tea
milk
0.001599786695107319
0.2857142857142857
2.2048794826572604
milk
soup
0.015197973603519531
0.11728395061728396
2.321231961953158
strong cheese
milk
0.0022663644847353685
0.29310344827586204
2.2619022278983962
whole wheat pasta
milk
0.009865351286495135
0.33484162895927605
2.5839990317114503
nonfat milk
mineral water
0.005065991201173177
0.4871794871794871
2.0438105891126024

In [32]:
for i in results:
  print(((i[2][0][2])))

0.25490196078431376
0.13725490196078433
0.14379084967320263
0.1111111111111111
0.16417910447761194
0.1343283582089552
0.2857142857142857
0.152
0.11111111111111112
0.132
0.13114754098360656
0.10465116279069768
0.3823529411764706
0.13846153846153847
0.2307692307692308
0.13846153846153847
0.18461538461538463
0.24615384615384614
0.12307692307692307
0.13846153846153847
0.24615384615384614
0.12307692307692307
0.36923076923076925
0.13846153846153847
0.15384615384615385
0.1851851851851852
0.1111111111111111
0.1111111111111111
0.19753086419753085
0.12345679012345678
0.2345679012345679
0.12149532710280372
0.14018691588785048
0.29906542056074764
0.14018691588785048
0.13043478260869565
0.13043478260869565
0.18840579710144928
0.15942028985507248
0.2608695652173913
0.11594202898550723
0.15942028985507248
0.14492753623188406
0.37681159420289856
0.37209302325581395
0.16279069767441862
0.10276679841897232
0.18461538461538463
0.2153846153846154
0.16923076923076924
0.15384615384615385
0.2727272727272727
0.1818181818181818
0.25
0.1818181818181818
0.40909090909090906
0.20253164556962025
0.25
0.1834319526627219
0.21105527638190955
0.1415929203539823
0.16766467065868262
0.1764705882352941
0.16326530612244897
0.21311475409836064
0.10434782608695653
0.11304347826086956
0.10434782608695653
0.13043478260869568
0.1565217391304348
0.16521739130434784
0.13043478260869568
0.25
0.1139896373056995
0.10880829015544043
0.12435233160621763
0.2746113989637306
0.19565217391304346
0.12658227848101267
0.11333333333333334
0.1616161616161616
0.23333333333333334
0.12074303405572756
0.1372549019607843
0.29059829059829057
0.1829268292682927
0.15286624203821658
0.1282051282051282
0.1347517730496454
0.13114754098360656
0.12903225806451613
0.1857142857142857
0.21739130434782608
0.19565217391304346
0.19565217391304346
0.3913043478260869
0.17391304347826084
0.3584905660377358
0.25
0.3548387096774194
0.4050632911392405
0.10126582278481013
0.31645569620253167
0.13924050632911394
0.12698412698412698
0.14285714285714285
0.2857142857142857
0.15873015873015872
0.19047619047619047
0.12698412698412698
0.25862068965517243
0.13333333333333336
0.10784313725490197
0.11227154046997388
0.10443864229765012
0.1794871794871795
0.12195121951219513
0.1282051282051282
0.11560693641618497
0.11510791366906474
0.11347517730496452
0.10443864229765012
0.10377358490566038
0.22950819672131148
0.15492957746478872
0.2222222222222222
0.15481171548117154
0.2424242424242424
0.1616161616161616
0.3006993006993007
0.3728813559322034
0.2413793103448276
0.1
0.12222222222222223
0.13333333333333336
0.47777777777777775
0.22222222222222224
0.2
0.11111111111111112
0.15555555555555556
0.3382352941176471
0.3448275862068966
0.1242603550295858
0.11242603550295857
0.12307692307692307
0.10059171597633135
0.15384615384615383
0.10975609756097561
0.11594202898550723
0.14035087719298245
0.12903225806451613
0.10778443113772455
0.1317365269461078
0.17964071856287428
0.16766467065868262
0.2275449101796407
0.14705882352941177
0.19607843137254902
0.2450980392156863
0.15384615384615385
0.18811881188118812
0.14814814814814814
0.1297709923664122
0.1347517730496454
0.23404255319148937
0.16981132075471697
0.1295336787564767
0.17142857142857143
0.23529411764705882
0.19230769230769232
0.27516778523489926
0.17482517482517482
0.20689655172413796
0.3448275862068966
0.1692307692307692
0.15384615384615385
0.15384615384615385
0.3076923076923077
0.2162849872773537
0.12468193384223919
0.17948717948717946
0.1347517730496454
0.12225705329153606
0.14150943396226418
0.13846153846153847
0.15384615384615385
0.39999999999999997
0.16176470588235295
0.11764705882352941
0.16176470588235295
0.2682926829268293
0.28888888888888886
0.29310344827586204
0.1628222523744912
0.2136752136752137
0.2424242424242424
0.14382632293080055
0.24623115577889446
0.20408163265306123
0.23404255319148934
0.21003134796238246
0.3989145183175034
0.3773584905660377
0.21311475409836064
0.23255813953488375
0.10891089108910891
0.1782178217821782
0.11881188118811882
0.10891089108910891
0.13567839195979897
0.1608040201005025
0.23076923076923075
0.23076923076923075
0.14529914529914528
0.10791366906474821
0.15602836879432624
0.16981132075471697
0.13114754098360656
0.12857142857142856
0.12669683257918551
0.11627906976744187
0.10791366906474821
0.15714285714285714
0.25531914893617025
0.30303030303030304
0.36363636363636365
0.2424242424242424
0.1111111111111111
0.20512820512820515
0.2222222222222222
0.1623931623931624
0.1623931623931624
0.20098039215686272
0.22413793103448276
0.15714285714285714
0.12195121951219513
0.3548387096774194
0.4782608695652174
0.19565217391304346
0.2611464968152866
0.18471337579617836
0.12738853503184713
0.2857142857142857
0.11728395061728396
0.29310344827586204
0.33484162895927605
0.4871794871794871
0.13986013986013987
0.19230769230769232
0.10256410256410255
0.14102564102564102
0.11538461538461538
0.15028901734104047
0.1347962382445141
0.13562753036437247
0.18965517241379312
0.19811320754716982
0.12145748987854252
0.1408450704225352
0.24285714285714283
0.16778523489932887
0.1610738255033557
0.10738255033557045
0.3220338983050847
0.37185929648241206
0.1457286432160804
0.2448979591836735
0.16326530612244897
0.20408163265306123
0.10071942446043165
0.1347517730496454
0.11594202898550723
0.36492890995260663
0.12264150943396225
0.10880829015544043
0.12857142857142856
0.11627906976744187
0.15671641791044774
0.14150943396226418
0.13720316622691292
0.4827586206896552
0.37931034482758624
0.4433962264150943
0.14285714285714285
0.10465116279069768

In [33]:
for i in (list(i[2][0])):
  print(i)

frozenset({'yams'})
frozenset({'whole wheat pasta'})
0.10465116279069768
3.551983584131327